# Generated by Django 3.2 on 2022-02-23 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
